/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoclase;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RAFAEL
 */
public class ListaProd extends javax.swing.JFrame {

    /**
     * Creates new form ListaProd
     */
    public ListaProd() {
        initComponents();
        productos = (DefaultTableModel)tab_prod.getModel();
        llenado_Produtos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tab_prod = new javax.swing.JTable();
        b_mat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista Productos");

        tab_prod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Producto", "Nombre", "id Categoria", "Categoria", "Precio", "Existencia"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tab_prod);
        if (tab_prod.getColumnModel().getColumnCount() > 0) {
            tab_prod.getColumnModel().getColumn(0).setPreferredWidth(90);
            tab_prod.getColumnModel().getColumn(1).setPreferredWidth(190);
            tab_prod.getColumnModel().getColumn(2).setPreferredWidth(90);
            tab_prod.getColumnModel().getColumn(3).setPreferredWidth(190);
        }

        b_mat.setText("Ver Matriz");
        b_mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_matActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_mat, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_mat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_matActionPerformed
        ProyectoClase.mat_productos.print_Grafica_matrix();
    }//GEN-LAST:event_b_matActionPerformed

    /**
     * @param args the command line arguments
     */
    DefaultTableModel productos;
    public void llenado_Produtos(){
//        //tab_prod.removeAllItems();
//        NodeProducto temp = ProyectoClase.mat_productos.head;
//        while (temp != null) { 
//            if (temp.idproducto_x != 0) {
//                if (temp.down != null) {
//                    NodeProducto temp_abj = temp.down; 
//                    productos.addRow(new Object[]{temp_abj.idproducto_x, temp_abj.nombrear,temp_abj.idcate_y, temp_abj.nombrecate , temp_abj.precio, temp_abj.unidades });
//                }
//                
//                
//            }
//            temp = temp.right;
//        }

    NodeProducto temp = ProyectoClase.mat_productos.head;
    while (temp != null) { 
  
            if (temp.down != null){
                NodeProducto temp_abj = temp.down;
                while (temp_abj != null) { 
                    
                    if (temp_abj.tipo.equals("N")) {
                         productos.addRow(new Object[]{temp_abj.idproducto_x, temp_abj.nombrear,temp_abj.idcate_y, temp_abj.nombrecate , temp_abj.precio, temp_abj.unidades });
                    }
                       

                    temp_abj = temp_abj.down;
                }
            }
        temp = temp.right;
    }  	

    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaProd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_mat;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tab_prod;
    // End of variables declaration//GEN-END:variables
}
