/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoclase;

import com.itextpdf.awt.DefaultFontMapper;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfTemplate;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.io.File;
import java.io.FileOutputStream;

/**
 *
 * @author RAFAEL
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Reportes
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_productos = new javax.swing.JButton();
        b_clientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        b_productos.setText("Inventario");
        b_productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_productosActionPerformed(evt);
            }
        });

        b_clientes.setText("Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(b_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(b_productos, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(b_productos, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_productosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_productosActionPerformed
        writeDocsPDF("productos.pdf");
    }//GEN-LAST:event_b_productosActionPerformed

    public static void writeDocsPDF(String fileName) {
    PdfWriter writer = null;
 
    Document document = new Document();
 
    try {
        writer = PdfWriter.getInstance(document, new FileOutputStream(fileName));
        document.open();

        /*  reportes de Productos  */
        document.newPage();
        document.add(new Paragraph("Reporte de Inventario (Productos)",
				FontFactory.getFont("arial",   // fuente
				20,                            // tamaño
				Font.ITALIC,                   // estilo
				BaseColor.BLUE)));
        document.bottom();
        document.add(new Paragraph("--"));
        document.add(new Paragraph(""));
        
        
//        int cont = 0;
//        for(ColaImpresion ca : cola){
//            cont++;
            //PdfPTable tabla = new PdfPTable(2);
            PdfPTable tabla = new PdfPTable(7);
            tabla.addCell("No.");
            tabla.addCell("id Producto");
            tabla.addCell("Nombre");
            
            tabla.addCell("id Categoria");
            tabla.addCell("Categoria");
            
            tabla.addCell("Precio");
            tabla.addCell("Existencia");
//            ca.getDim1(); dimension1
//            ca.getDimension(); dimension2 graficar
//            ca.getMetrica(); metricas



////            for (int i = 0; i < dim2_im.length; i++) {
//            for (int i = 0; i < ca.getDimension().length ; i++) {
////                JOptionPane.showMessageDialog(null, "dim2_im["+i+"]: " + dim2_im[i]);
//                tabla.addCell(String.valueOf(i +1));
//                tabla.addCell(ca.getDimension()[i]);
//                tabla.addCell(String.valueOf(ca.getMetrica()[i] ));
////                tabla.addCell(ca.getGrafica().toString());
//                
//            }

    NodeProducto temp = ProyectoClase.mat_productos.head;
    int conta = 0;
    while (temp != null) { 
  
            if (temp.down != null){
                NodeProducto temp_abj = temp.down;
                while (temp_abj != null) { 
                    
                    if (temp_abj.tipo.equals("N")) {
                        conta++;
                        tabla.addCell(String.valueOf(conta));
                        tabla.addCell(String.valueOf(temp_abj.idproducto_x));
                        tabla.addCell(String.valueOf(temp_abj.nombrear));
                        
                        tabla.addCell(String.valueOf(temp_abj.idcate_y));
                        tabla.addCell(String.valueOf(temp_abj.nombrecate));
                        
                        tabla.addCell(String.valueOf(temp_abj.precio));
                        tabla.addCell(String.valueOf(temp_abj.unidades));
                        //productos.addRow(new Object[]{temp_abj.idproducto_x, temp_abj.nombrear,temp_abj.idcate_y, temp_abj.nombrecate , temp_abj.precio, temp_abj.unidades });
                    }
                       

                    temp_abj = temp_abj.down;
                }
            }
        temp = temp.right;
    } 
    
            
            
            tabla.spacingAfter();
            document.add(tabla);
            
//        PdfContentByte contentByte = writer.getDirectContent();
//        PdfTemplate template = contentByte.createTemplate(width, height);
//
//            Graphics2D graphics2d = template.createGraphics(width, height, new DefaultFontMapper());
//            Rectangle2D rectangle2d = new Rectangle2D.Double(0, 0, width, height);
//            
//            ca.getGrafica().draw(graphics2d, rectangle2d );
//            graphics2d.dispose();
//            contentByte.addTemplate(template, 20, 10);
//
////////            contentByte.addTemplate(template, 0,0);

            document.newPage();
            
//        }
//        
   
        
//        JOptionPane.showMessageDialog(null, "asdfsadfasdfasdfvcfadsfasdfasdfasdfasdfasfasdf");
//        for (int i = 0; i < dim2_im.length; i++) {
//            JOptionPane.showMessageDialog(null, "dim2_im["+i+"]: " + dim2_im[i]);
//            tabla.addCell(dim2_im[i]);
//            tabla.addCell(String.valueOf(met_im[i] ));
//        }
        

        document.close();
        Desktop.getDesktop().open(new File("productos.pdf"));
        
    } catch (Exception e) {
        e.printStackTrace();
        document.close();
    }
    

    
////    JOptionPane.showMessageDialog(null,"El proceso se realizó con éxito");
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_clientes;
    private javax.swing.JButton b_productos;
    // End of variables declaration//GEN-END:variables
}
